name: Sample Pipeline CI/CD

on: [push]

jobs:
  build python app:

    runs-on: ubuntu-latest
      python-version: 3.7

    steps:
    - uses: actions/checkout@v1

    - name: Set up Python on Ubuntu Image
      uses: actions/setup-python@v1
      with:
        python-version: 3.7

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Test with pytest
      run: |
        pip install pytest
        pytest

    - name: Further Steps ..Do whatever you want in the next stage
